name: Environment Variables
on: 
  push:
    branches:
      - master
env:
  DB_NAME: ${{secrets.DB_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables
        run: echo "Database Name $DB_NAME"